name: Helium Test Workflow

on:
  push:
    branches: [ main, feature** ]
  pull_request:
    branches: [ main, feature** ]
  workflow_dispatch:
  schedule:
    # Runs daily at 20:33 IST (15:03 UTC)
    #- cron: '3 15 * * *'
    # Runs every 5 minutes
    # - cron: '*/5 * * * *'

jobs:
  helium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget -q https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.83/linux64/chrome-linux64.zip
          wget -q https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.83/linux64/chromedriver-linux64.zip
          unzip chrome-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chrome-linux64 /usr/local/share/chrome
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo ln -s /usr/local/share/chrome/chrome /usr/local/bin/google-chrome
          google-chrome --version
          chromedriver --version

      - name: Run Helium validation
        env:
          PATH: /usr/local/bin:$PATH
        run: |
          python tests/helium_test.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helium-artifacts
          path: artifacts/screenshots/
